import Foundation

enum PasteboardPrivacyMarker {
    static let transient: [String] = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.transienttype",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping"
    ]

    static let concealed: [String] = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.concealedtype",
        "com.agilebits.onepassword"
    ]

    static let autoGenerated: [String] = [
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.autogeneratedtype"
    ]

    static let internalWrite = AppIdentity.internalPasteboardType

    static func shouldSkip(_ typeIdentifiers: [String]) -> Bool {
        let lowered = Set(typeIdentifiers.map { $0.lowercased() })
        let all = (transient + concealed + autoGenerated + [internalWrite]).map { $0.lowercased() }
        return all.contains { lowered.contains($0) }
    }

    static func isInternalWrite(_ typeIdentifiers: [String]) -> Bool {
        typeIdentifiers.contains { $0.caseInsensitiveCompare(internalWrite) == .orderedSame }
    }
}

enum ClipboardContentParser {
    static func parse(_ snapshot: PasteboardSnapshot) -> ParsedClipboard? {
        if PasteboardPrivacyMarker.shouldSkip(snapshot.typeIdentifiers) {
            return nil
        }

        if !snapshot.fileURLs.isEmpty {
            let paths = snapshot.fileURLs.map(\.path)
            let names = snapshot.fileURLs.map(\.lastPathComponent)
            let preview = names.joined(separator: ", ")
            return ParsedClipboard(
                kind: .file,
                plainText: paths.joined(separator: "\n"),
                urlString: snapshot.fileURLs.first?.absoluteString,
                previewText: preview,
                filePaths: paths,
                fileNames: names,
                rtfData: snapshot.rtf,
                htmlData: snapshot.html,
                imageData: nil,
                contentHash: ClipboardHasher.hashFiles(paths)
            )
        }

        if let image = snapshot.imageTIFF, !image.isEmpty {
            return ParsedClipboard(
                kind: .image,
                plainText: nil,
                urlString: nil,
                previewText: "Image",
                filePaths: [],
                fileNames: [],
                rtfData: nil,
                htmlData: nil,
                imageData: image,
                contentHash: ClipboardHasher.hashImage(image)
            )
        }

        let rawString = snapshot.string?.trimmingCharacters(in: .whitespacesAndNewlines)
        let urlCandidate = (snapshot.urlString ?? rawString).flatMap(Self.recognizedURL)

        if let urlCandidate {
            return ParsedClipboard(
                kind: .url,
                plainText: urlCandidate,
                urlString: urlCandidate,
                previewText: urlCandidate,
                filePaths: [],
                fileNames: [],
                rtfData: snapshot.rtf,
                htmlData: snapshot.html,
                imageData: nil,
                contentHash: ClipboardHasher.hashURL(urlCandidate)
            )
        }

        if let rawString, !rawString.isEmpty {
            let hasRich = (snapshot.rtf?.isEmpty == false) || (snapshot.html?.isEmpty == false)
            return ParsedClipboard(
                kind: hasRich ? .richText : .text,
                plainText: rawString,
                urlString: nil,
                previewText: rawString,
                filePaths: [],
                fileNames: [],
                rtfData: snapshot.rtf,
                htmlData: snapshot.html,
                imageData: nil,
                contentHash: ClipboardHasher.hashPlainText(rawString)
            )
        }

        return nil
    }

    static func recognizedURL(_ raw: String) -> String? {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, !trimmed.contains(where: \.isNewline) else { return nil }

        if let url = URL(string: trimmed), let scheme = url.scheme?.lowercased() {
            let allowed = ["http", "https", "ftp", "file", "mailto"]
            if allowed.contains(scheme) {
                if scheme == "mailto" || scheme == "file" || url.host != nil {
                    return trimmed
                }
            }
        }

        if trimmed.hasPrefix("www."), trimmed.contains("."), !trimmed.contains(" ") {
            return "https://\(trimmed)"
        }

        return nil
    }

    static func previewLines(_ text: String, limit: Int = 4) -> String {
        let lines = text.split(whereSeparator: \.isNewline).map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
        return lines.prefix(limit).joined(separator: "\n")
    }
}
